version: '3.8'

services:
  radar-app:
    build: .
    container_name: radar_v1_app
    restart: always
    env_file:
      - .env
    network_mode: host
    command: ["gunicorn", "--bind", "0.0.0.0:8005", "--workers", "4", "--timeout", "120", "--access-logfile", "-", "app:app"]
    volumes:
      - .:/app
      - ./data:/app/data
      - ./imports:/app/imports
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Networks removed as we are using network_mode: host
